spring.datasource:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: 
spring.jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  database: MYSQL
  show-sql: true
  generate-ddl: false
  hibernate:
      ddl-auto: none
  properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: update
#      hibernate.hbm2ddl.auto: create-drop
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
management.security.enabled: false
server:
  port: 8082 
      